FROM alpine:3

EXPOSE 3000

RUN apk add --no-cache npm

RUN npm install -g pnpm@next-7 nodemon ts-node

RUN mkdir /app
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN rm -rf ./src

RUN pnpm run generate-prisma

ENTRYPOINT ["npx", "nodemon"]