service: payme-be-graphql
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: 512
functions:
  graphql:
    handler: src/apollo-server-lambda.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  webpack:
    includeModules: true
  prune:
    automatic: true
    number: 2
frameworkVersion: ^3.2.1
package:
  excludeDevDependencies: true
  individually: true
