service: payme-be-graphql
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
functions:
  graphql:
    handler: src/apollo-server-lambda.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline
custom:
  webpack:
    includeModules: true 
frameworkVersion: ^3.2.1
package:
  excludeDevDependencies: true
  individually: true
    